### ISSUE TITLE
Get current producer useless? 

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [EOSIO/spec-repo#11]
[get current producer](https://github.com/EOSIO/spec-repo/blob/master/esr_get_producer.md) 

It seems to me this proposal has absolutely the same issue it is suppose to solve. It suppose to allow smart contracts not to run on nodes which are messing up with subjective data like cpu cost. But this nodes can also return incorrect data for get_current_producer call. It does Not solve the problem. It just hides it a little. :)

**Comment by tbfleming** [comment]
The other nodes won't lie when they validate the block. This will cause a state difference which has the potential to fork away the lying BP.

**Comment by Vasiliy-Bondarenko** [comment]
ok.
