### ISSUE TITLE
flexible notify event example

### ISSUE THREAD

**Issue by slyon** [EOSIO/spec-repo#13]
[esr_flexible_notify](https://github.com/EOSIO/spec-repo/blob/master/esr_flexible_notify.md)

What would be an example of a "contract-to-outside" event?

Is it supposed to be only used inside nodeos for BPs to handle IBC/IRC with sister chains, or would it also allow for REST-API calls to be triggered outside the blockchain?

**Comment by tbfleming** [comment]
The state-history plugin exposes all inline actions, so anything outside of nodeos could listen for these events. So, for example, you could create a process which monitors for certain events then:
* Populates a database, or
* Sends an email or IM, or
* Makes a REST request to a server, or
* Causes a robot arm to move

**Comment by slyon** [comment]
Thanks for the explanation, this helps to understand the situation better. We should consider adding this note to the ESR summary.

See PR https://github.com/EOSIO/spec-repo/pull/15
